/** @type {import("tailwindcss").Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  plugins: [],
  theme: {
    extend: {
      borderRadius: {
        app: "var(--radius-app)",
        control: "var(--radius-control)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        panel: "var(--radius-panel)",
        row: "var(--radius-row)",
        sm: "calc(var(--radius) - 4px)",
        surface: "var(--radius-surface)",
        window: "var(--radius-window)",
      },
      colors: {
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        background: "hsl(var(--background))",
        border: "hsl(var(--border))",
        "border-control": "hsl(var(--border-control))",
        "border-divider": "hsl(var(--border-divider))",
        "border-panel": "hsl(var(--border-panel))",
        "border-subtle": "hsl(var(--border-subtle))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        "control-surface": "hsl(var(--control-surface))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        foreground: "hsl(var(--foreground))",
        input: "hsl(var(--input))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        "panel-surface": "hsl(var(--panel-surface))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        ring: "hsl(var(--ring))",
        "search-border": "hsl(var(--search-border))",
        "search-surface": "hsl(var(--search-surface))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        "segmented-surface": "hsl(var(--segmented-surface))",
      },
      fontFamily: {
        sans: ['"SF Pro Text"', '"Segoe UI"', "ui-sans-serif", "sans-serif"],
      },
      fontSize: {
        body: ["14px", { lineHeight: "1.25" }],
        "body-sm": ["13px", { lineHeight: "1.4" }],
        caption: ["11px", { lineHeight: "1.25" }],
        input: ["15px", { lineHeight: "1.4" }],
        meta: ["12px", { lineHeight: "1.3" }],
        "section-title": ["18px", { lineHeight: "1" }],
      },
    },
  },
};
